Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте
все элементы массива на 2, а затем замените все элементы больше 10 на 0.
Выведите итоговый массив

In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a * 2)

for i in range(3):
    for j in range(3):
        if a[i, j] > 10:  
            a[i, j] = 0

print(a)

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и
выведите все элементы, которые делятся на 5 без остатка. Затем замените их на
-1 и выведите обновленный массив

In [8]:
import numpy as np
a = np.random.randint(1, 100, 20)
print(a)
a[a%5==0]=-1
print(a)

[24 44  1 99  3 45 43 18 61  4 52 98 38 80 38 87 39 85 59 67]
[24 44  1 99  3 -1 43 18 61  4 52 98 38 -1 38 87 39 -1 59 67]


Создайте два массива NumPy размером 1×5, заполненные случайными числами
от 0 до 50.
Выведите все промежуточные и итоговые результаты.

In [ ]:
import numpy as np
a = np.random.randint(0, 50, size = (1, 5))
a1 = np.random.randint(0, 50, size = (1, 5))
result = np.vstack((a, a1))
b = result[0, :]
b1 = result[1, :]
print(a)
print(a1)
print()
print(result)
print()
print(b)
print(b1)


Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.
Вычислите сумму всех элементов, сумму положительных элементов и сумму
отрицательных элементов. Выведите результаты.

In [ ]:
import numpy as np
mas = np.random.normal(-10, 10, 50)
print(mas)
summ, sum_poz, sum_neg = 0, 0, 0
for i in range(len(mas)):
    summ+=mas[i]
    if mas[i]>0:
        sum_poz+=mas[i]
    elif mas[i]<0:
        sum_neg+=mas[i]
            
print(summ, sum_poz, sum_neg)

Создайте:
Единичную матрицу размером 4×4.
Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы).
Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [15]:
import numpy as np
a = np.eye(4)
sum_el_a, sum_el_a1 = 0, 0
m = [5, 10, 15, 20]
m_diag = np.diag(m)
a1 = np.array(m_diag)
for row in a:
    for col in row:
        sum_el_a += col
for row in a1:
    for col in row:
        sum_el_a1 += col
print(sum_el_a, sum_el_a1)

4.0 50


Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:
Их сумму
Их разность
Их поэлементное произведение

In [ ]:
import numpy as np  
a = np.random.randint(1, 20, size=(3, 3))  
a1 = np.random.randint(1, 20, size=(3, 3))  
print(a + a1, "\n")  
print(a - a1, "\n")  
print(a * a1, "\n")

Создайте две матрицы NumPy:
Первую размером 2×3, заполненную случайными числами от 1 до 10.
Вторую размером 3×2, заполненную случайными числами от 1 до 10.
Выполните матричное умножение (используя оператор @ или функцию np.dot) и выведите результат.

In [ ]:
import numpy as np
matrix1 = np.random.randint(1, 10, size = (2, 3))
matrix2 = np.random.randint(1, 10, size = (3, 2))
print(np.dot(matrix1, matrix2))

Создайте случайную квадратную матрицу 3×3. Найдите и выведите:
Определитель этой матрицы (используйте np.linalg.det).
Обратную матрицу (используйте np.linalg.inv). Если матрица вырождена (определитель равен 0), выведите сообщение, что матрица вырождена.

In [4]:
import numpy as np
matrix = np.random.randint(1, 20, size=(3, 3))
det = np.linalg.det(matrix)
if det == 0:
    print("матрица вырождена")
inv = np.linalg.inv(matrix)
print(det)
print(inv)

-468.00000000000017
[[-4.27350427e-03  7.69230769e-02 -2.13675214e-02]
 [ 3.61111111e-01  1.07237451e-17 -1.94444444e-01]
 [-1.62393162e-01 -7.69230769e-02  1.88034188e-01]]


Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите:
Исходную матрицу
Транспонированную матрицу
След матрицы (сумму элементов на главной диагонали)
Используйте np.trace для нахождения следа.

In [ ]:
import numpy as np
matrix = np.random.randint(1, 50, size = (4,4))
trace = np.trace(matrix)
print(matrix)
print(np.transpose(matrix))
print(trace)


Решите систему линейных уравнений вида:
2x+3y-z=5
4x-y+2z=6
-3x+5y+4z=-2
Используйте матричное представление Ax = B , где A – матрица коэффициентов,
x – вектор неизвестных, B – вектор правой части. Решите систему с помощью
np.linalg.solve и выведите результат

In [ ]:
import numpy as np
A = np.array([[2, 3, -1], [4, -1, 2], [-3, 5, 4]])
B = [5, 6, -2]
solution = np.linalg.solve(A, B)
print(solution)

Решите индивидуальное задание согласно вашему варианту. Каждое задание предусматривает построение системы линейных уравнений. Решите полученную систему уравнений с использованием библиотеки NumPy. Для решения системы используйте:
Метод Крамера
Матричный метод
Сравните полученные результаты с результатами, полученными с помощью np.linalg.solve

Компания выделила 1 500 000 рублей
на рекламу в интернете, на телевидении и в печатных изданиях. На интернет-
рекламу выделяется в 2 раза больше, чем на печатные издания, а на
телевидение — на 500 000 рублей больше, чем на печатные издания. Как
распределены деньги?

In [ ]:
import numpy as np
# решение матричным методом
A = np.array([[1,1,1], 
            [-2, 1, 0], 
            [-1, 0, 1]])
A_inv = np.linalg.inv(A)#обратная матрица
B = [1500000, 0, 500000]
X = np.dot(A_inv, B)
print(X[0], '- Печатные издания')
print(X[1], '- Интернет реклама')
print(X[2],  '- Телевидение')
# Решение методом крамера
det_A = np.linalg.det(A)
A1 = A.copy()
A2 = A.copy()
A3 = A.copy()
# Заменяем столбцы на вектор B
A1[:, 0] = B   
A2[:, 1] = B  
A3[:, 2] = B  
#Вычисляем определители новых матриц
det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)
det_A3 = np.linalg.det(A3)
# находим иксы
x1 = det_A1 / det_A
x2 = det_A2 / det_A
x3 = det_A3 / det_A
print(f"Печатные издания: {int(x1)} рублей")
print(f"Интернет-реклама: {int(x2)} рублей")
print(f"Телевидение: {int(x3)} рублей")
#проверка третьим способом
print(np.linalg.solve(A, B))