Задание 1

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте
все элементы массива на 2, а затем замените все элементы больше 10 на 0.
Выведите итоговый массив

In [6]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a * 2)

for i in range(3):
    for j in range(3):
        if a[i, j] > 10:  
            a[i, j] = 0

print(a)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Задание 2

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и
выведите все элементы, которые делятся на 5 без остатка. Затем замените их на
-1 и выведите обновленный массив

In [8]:
import numpy as np
a = np.random.randint(1, 100, 20)
print(a)
a[a%5==0]=-1
print(a)

[27 85 92 73 79 46 93 47 61 80 14  1 22 32 72 52  2 36 60 57]
[27 -1 92 73 79 46 93 47 61 -1 14  1 22 32 72 52  2 36 -1 57]


Задание 3

Создайте два массива NumPy размером 1×5, заполненные случайными числами
от 0 до 50.
Выведите все промежуточные и итоговые результаты.

In [10]:
import numpy as np
a = np.random.randint(0, 50, size = (1, 5))
a1 = np.random.randint(0, 50, size = (1, 5))
result = np.vstack((a, a1))
b = result[0, :]
b1 = result[1, :]
print(a)
print(a1)
print()
print(result)
print()
print(b)
print(b1)


[[12 33 34 22 21]]
[[36 17 36 46  8]]

[[12 33 34 22 21]
 [36 17 36 46  8]]

[12 33 34 22 21]
[36 17 36 46  8]


Задание 4

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.
Вычислите сумму всех элементов, сумму положительных элементов и сумму
отрицательных элементов. Выведите результаты.

In [41]:
import numpy as np
mas = np.random.uniform(-10, 10, 50)
print(mas)

summ, sum_poz, sum_neg = 0, 0, 0
for i in range(len(mas)):
    summ+=mas[i]
    if mas[i]>0:
        sum_poz+=mas[i]
    elif mas[i]<0:
        sum_neg+=mas[i]
            
print(summ, sum_poz, sum_neg)

[ 4.66814866 -9.09392089 -0.49683922  2.76134778 -3.50148832  3.75187634
 -2.89660097 -6.1372709  -4.18817537 -3.48873124 -6.43913346  3.8904525
 -1.77779143  1.0332751  -7.69613118  5.67589017 -4.33864918  6.80436019
 -3.04664984 -2.27204018 -6.03650033  1.33777834  0.14353279 -2.15830887
  0.82459046 -3.40948192  2.27652801  8.57841835  5.16770879 -9.75792756
  0.50285932 -8.1647054  -0.86912549 -9.79836545  8.33685812  8.79150141
  1.17272352  8.68411623 -7.46519998 -2.05559142 -4.97233103 -3.94007423
  2.38039548 -8.16871803 -5.23516095  3.16886582  2.95350172 -7.04603761
 -4.79883735 -0.35764254]
-56.702701264749834 82.90472909480079 -139.60743035955056


Задание 5

Создайте:
Единичную матрицу размером 4×4.
Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы).
Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [14]:
import numpy as np
a = np.eye(4)
sum_el_a, sum_el_a1 = 0, 0
m = [5, 10, 15, 20]
m_diag = np.diag(m)
a1 = np.array(m_diag)
for row in a:
    for col in row:
        sum_el_a += col
for row in a1:
    for col in row:
        sum_el_a1 += col
print(sum_el_a, sum_el_a1)

4.0 50


Задание 6

Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:
Их сумму
Их разность
Их поэлементное произведение

In [16]:
import numpy as np  
a = np.random.randint(1, 20, size=(3, 3))  
a1 = np.random.randint(1, 20, size=(3, 3))  
print(a + a1, "\n")  
print(a - a1, "\n")  
print(a * a1, "\n")

[[23 20 11]
 [27 30 15]
 [29 21 16]] 

[[ -1   4  -5]
 [  9  -4  13]
 [ -5 -15   6]] 

[[132  96  24]
 [162 221  14]
 [204  54  55]] 



Задание 7

Создайте две матрицы NumPy:
Первую размером 2×3, заполненную случайными числами от 1 до 10.
Вторую размером 3×2, заполненную случайными числами от 1 до 10.
Выполните матричное умножение (используя оператор @ или функцию np.dot) и выведите результат.

In [18]:
import numpy as np
matrix1 = np.random.randint(1, 10, size = (2, 3))
matrix2 = np.random.randint(1, 10, size = (3, 2))
print(np.dot(matrix1, matrix2))

[[21 43]
 [36 67]]


Задание 8

Создайте случайную квадратную матрицу 3×3. Найдите и выведите:
Определитель этой матрицы (используйте np.linalg.det).
Обратную матрицу (используйте np.linalg.inv). Если матрица вырождена (определитель равен 0), выведите сообщение, что матрица вырождена.

In [20]:
import numpy as np
matrix = np.random.randint(1, 20, size=(3, 3))
det = np.linalg.det(matrix)
if det == 0:
    print("матрица вырождена")
inv = np.linalg.inv(matrix)
print(det)
print(inv)

202.99999999999977
[[-0.05418719  0.00492611  0.19211823]
 [ 0.46305419 -0.13300493 -0.18719212]
 [-0.08374384  0.09852217 -0.15763547]]


Задание 9

Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите:
Исходную матрицу
Транспонированную матрицу
След матрицы (сумму элементов на главной диагонали)
Используйте np.trace для нахождения следа.

In [22]:
import numpy as np
matrix = np.random.randint(1, 50, size = (4,4))
trace = np.trace(matrix)
print(matrix)
print(np.transpose(matrix))
print(trace)


[[ 7 29 33 18]
 [ 1 27 45 22]
 [ 6 29  2  6]
 [18 43  9 45]]
[[ 7  1  6 18]
 [29 27 29 43]
 [33 45  2  9]
 [18 22  6 45]]
81


Задание 10

Решите систему линейных уравнений вида:
2x+3y-z=5
4x-y+2z=6
-3x+5y+4z=-2
Используйте матричное представление Ax = B , где A – матрица коэффициентов,
x – вектор неизвестных, B – вектор правой части. Решите систему с помощью
np.linalg.solve и выведите результат

In [24]:
import numpy as np
A = np.array([[2, 3, -1], [4, -1, 2], [-3, 5, 4]])
B = [5, 6, -2]
solution = np.linalg.solve(A, B)
print(solution)

[1.63963964 0.57657658 0.00900901]


Решите индивидуальное задание согласно вашему варианту (26). Каждое задание предусматривает построение системы линейных уравнений. Решите полученную систему уравнений с использованием библиотеки NumPy. Для решения системы используйте:
Метод Крамера
Матричный метод
Сравните полученные результаты с результатами, полученными с помощью np.linalg.solve

Компания выделила 1 500 000 рублей
на рекламу в интернете, на телевидении и в печатных изданиях. На интернет-
рекламу выделяется в 2 раза больше, чем на печатные издания, а на
телевидение — на 500 000 рублей больше, чем на печатные издания. Как
распределены деньги?

In [26]:
import numpy as np
# сама система
# x + y + z = 1500000
# y = 2x
# z = x + 500000
# решение матричным методом
A = np.array([[1,1,1], 
            [-2, 1, 0], 
            [-1, 0, 1]])
A_inv = np.linalg.inv(A)#обратная матрица
B = [1500000, 0, 500000]
X = np.dot(A_inv, B)
print(X[0], '- Печатные издания')
print(X[1], '- Интернет реклама')
print(X[2],  '- Телевидение')

# Решение методом крамера
det_A = np.linalg.det(A)
A1 = A.copy()
A2 = A.copy()
A3 = A.copy()
# Заменяем столбцы на вектор B
A1[:, 0] = B   
A2[:, 1] = B  
A3[:, 2] = B  
#Вычисляем определители новых матриц
det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)
det_A3 = np.linalg.det(A3)
# находим иксы
x1 = det_A1 / det_A
x2 = det_A2 / det_A
x3 = det_A3 / det_A
print(f"Печатные издания: {int(x1)} рублей")
print(f"Интернет-реклама: {int(x2)} рублей")
print(f"Телевидение: {int(x3)} рублей")

#проверка третьим способом
print(np.linalg.solve(A, B))

250000.0 - Печатные издания
500000.0 - Интернет реклама
750000.0 - Телевидение
Печатные издания: 250000 рублей
Интернет-реклама: 500000 рублей
Телевидение: 749999 рублей
[250000. 500000. 750000.]
