## Задание 1

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте
все элементы массива на 2, а затем замените все элементы больше 10 на 0.
Выведите итоговый массив

In [14]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = a*2
a[a>10]=0

print("Матрица с заменеными элементами ",'\n',  a)

Матрица с заменеными элементами  
 [[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


## Задание 2

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и
выведите все элементы, которые делятся на 5 без остатка. Затем замените их на
-1 и выведите обновленный массив

In [16]:
a = np.random.randint(1, 100, 20)
print(a, '\n')

print("Элеметы делящиеся нацело на пять", a[a%5==0], '\n')

a[a%5==0]=-1

print("Массив с заменеными элементами", a)

[82 42 27 63 66 64 96 97 31 76 23 35 38 47 40 53 87 70 92 83] 

Элеметы делящиеся нацело на пять [35 40 70] 

Массив с заменеными элементами [82 42 27 63 66 64 96 97 31 76 23 -1 38 47 -1 53 87 -1 92 83]


## Задание 3

Создайте два массива NumPy размером 1×5, заполненные случайными числами
от 0 до 50.
Выведите все промежуточные и итоговые результаты.

In [18]:
a = np.random.randint(0, 50, size = (1, 5))
a1 = np.random.randint(0, 50, size = (1, 5))

result = np.vstack((a, a1))

b = result[0, :]
b1 = result[1, :]
print(a)
print(a1)
print()
print(result)
print()
print(b)
print(b1)


[[ 1  6 47 39 18]]
[[ 5 37 18 17 23]]

[[ 1  6 47 39 18]
 [ 5 37 18 17 23]]

[ 1  6 47 39 18]
[ 5 37 18 17 23]


## Задание 4

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.
Вычислите сумму всех элементов, сумму положительных элементов и сумму
отрицательных элементов. Выведите результаты.

In [20]:
mas = np.random.uniform(-10, 10, 50)
print(mas, '\n')

summ=sum(mas)
sum_poz = sum(mas[mas>0])
sum_neg = sum(mas[mas<0]) 

print('Сумма = ', summ)
print('Сумма положительных = ', sum_poz)
print('Сумма отрицательных = ', sum_neg)

[ 7.74425577 -8.03709105 -3.32364695 -3.91654482  4.47119184  4.62042487
  7.70891909  8.53545011  3.18463746 -3.18805518 -5.48063858 -3.64664837
 -4.32502769 -2.20353056  1.6512482   9.2915637  -1.98558985  5.61558644
 -4.61932832 -0.38976834  8.60888568  3.98000267 -1.12884225  6.68287331
 -9.24033293  6.2805006  -3.07076835 -7.56178181 -2.58452003 -5.70892946
  1.81209774 -4.09910399  3.31853967 -7.55171249  9.1654147  -7.35118002
 -2.2423143  -6.51669477 -0.34340551 -3.67906139 -0.2213407  -3.12682854
 -7.33185297 -9.03558331  0.13079525 -3.59887673 -9.93871306  0.18816312
  5.5815091  -8.66313238] 

Сумма =  -45.53878536614488
Сумма положительных =  98.57205930857765
Сумма отрицательных =  -144.1108446747225


## Задание 5

Создайте:
Единичную матрицу размером 4×4.
Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы).
Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [22]:
a = np.eye(4)
m = [5, 10, 15, 20]
m_diag = np.diag(m)
a1 = np.array(m_diag)

sum_el_a = np.sum(a)
sum_el_a1 = np.sum(a1)

print('Суммма  элементов матрицы a = ',sum_el_a) 
print('Суммма элементов мтарицы а1 = ', sum_el_a1)

Суммма  элементов матрицы a =  4.0
Суммма элементов мтарицы а1 =  50


## Задание 6

Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:
Их сумму
Их разность
Их поэлементное произведение

In [24]:
a = np.random.randint(1, 20, size=(3, 3))  
a1 = np.random.randint(1, 20, size=(3, 3))  

print('Сумма матриц',"\n",  a + a1, "\n")  
print('Разность матриц ', "\n", a - a1, "\n")  
print('Поэлементое произведение',"\n",  a * a1, "\n")

Сумма матриц 
 [[23 11 21]
 [25 25 14]
 [13 13 24]] 

Разность матриц  
 [[ 3 -9 17]
 [-3 -5  2]
 [ 5 -5  6]] 

Поэлементое произведение 
 [[130  10  38]
 [154 150  48]
 [ 36  36 135]] 



## Задание 7

Создайте две матрицы NumPy:
Первую размером 2×3, заполненную случайными числами от 1 до 10.
Вторую размером 3×2, заполненную случайными числами от 1 до 10.
Выполните матричное умножение (используя оператор @ или функцию np.dot) и выведите результат.

In [26]:
matrix1 = np.random.randint(1, 10, size = (2, 3))
matrix2 = np.random.randint(1, 10, size = (3, 2))

print(matrix1,'\n')
print(matrix2, '\n')
print(np.dot(matrix1, matrix2))

[[3 3 1]
 [9 8 9]] 

[[2 8]
 [2 6]
 [1 3]] 

[[ 13  45]
 [ 43 147]]


## Задание 8

Создайте случайную квадратную матрицу 3×3. Найдите и выведите:
Определитель этой матрицы (используйте np.linalg.det).
Обратную матрицу (используйте np.linalg.inv). Если матрица вырождена (определитель равен 0), выведите сообщение, что матрица вырождена.

In [28]:
matrix = np.random.randint(1, 20, size=(3, 3))
det = np.linalg.det(matrix)

if det == 0:
print("матрица вырождена")

inv = np.linalg.inv(matrix)
print('Определитель = ', det)
print('Oбратная матица ','\n', inv)

Определитель =  -1206.0000000000005
Oбратная матица  
 [[ 0.13930348  0.18325041 -0.24461028]
 [ 0.07462687 -0.01492537 -0.02985075]
 [-0.09452736 -0.05887231  0.16003317]]


## Задание 9

Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите:
Исходную матрицу
Транспонированную матрицу
След матрицы (сумму элементов на главной диагонали)
Используйте np.trace для нахождения следа.

In [30]:
matrix = np.random.randint(1, 50, size = (4,4))
trace = np.trace(matrix)

print(matrix, '\n')
print('Транспонированная матрица', '\n', np.transpose(matrix), '\n')
print('След = ', trace)

[[20 29 31 29]
 [ 1 43  2  1]
 [43 46  2 30]
 [42 20 44 39]] 

Транспонированная матрица 
 [[20  1 43 42]
 [29 43 46 20]
 [31  2  2 44]
 [29  1 30 39]] 

След =  104


## Задание 10

Решите систему линейных уравнений вида:

\begin{equation*}
 \begin{cases}
   2x+3y-z=5, 
   \\
    4x-y+2z=6 ,
   \\
   -3x+5y+4z=-2.
 \end{cases}
\end{equation*}

Используйте матричное представление Ax = B , где A – матрица коэффициентов,
x – вектор неизвестных, B – вектор правой части. Решите систему с помощью
np.linalg.solve и выведите результат


In [32]:
A = np.array([[2, 3, -1], [4, -1, 2], [-3, 5, 4]])
B = [5, 6, -2]

solution = np.linalg.solve(A, B)

print(solution)

[1.63963964 0.57657658 0.00900901]


## Решите индивидуальное задание согласно вашему варианту (26). 
Для создания нового металлического сплава
используются три вида металлов. 

Первый содержит 40% железа, второй —
60%, третий — 80%. 

Нужно получить 200 кг сплава с 65% железа, при этом
второго металла должно быть в два раза больше, чем первого. Сколько
килограммов каждого металла нужно взять?

Обозначим за x количество кг первого металла, за y и z - у вторго и третьего соответственно

Сумма трех металлов помноженных на и на количество сплава должно быть равно 200*0.65 кг, что равно 130кг

Сумммарная масса трех металлов без сплавов равна 200 кг

так как второго металла в два раза больше чем первого последняя подсистема будет иметь вид 2x-y=0 

Итого получим система следущего вида :

\begin{equation*}
 \begin{cases}
   0,4x+0,6y+0,8z=130, 
   \\
    x+y+z=200 ,
   \\
   2x-y=0.
 \end{cases}
\end{equation*}

In [75]:
# решение матричным методом
A = np.array([[0.4,0.6,0.8], 
            [1, 1, 1], 
            [2, -1, 0]])
A_inv = np.linalg.inv(A)#обратная матрица
B = [130, 200, 0]
X = np.dot(A_inv, B)
print(X[0], '- кг первого металла')
print(X[1], '- кг второого металла')
print(X[2], '- кг третьего металла', '\n')

# Решение методом крамера
det_A = np.linalg.det(A)
A1 = A.copy()
A2 = A.copy()
A3 = A.copy()
# Заменяем столбцы на вектор B

A1[:, 0] = B   
A2[:, 1] = B  
A3[:, 2] = B  
#Вычисляем определители новых матриц

det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)
det_A3 = np.linalg.det(A3)
# находим иксы

x1 = det_A1 / det_A
x2 = det_A2 / det_A
x3 = det_A3 / det_A
print(f"Первый металл присутвует в количестве : {(x1)} кг")
print(f"Второй металл содержится в количестве: {(x2)} кг")
print(f"Третий металл содержится в количестве: {(x3)} кг", '\n')

#проверка третьим способом
print(np.linalg.solve(A, B))

37.5 - кг первого металла
75.0 - кг второого металла
87.5 - кг третьего металла 

Первый металл присутвует в количестве : 37.499999999999986 кг
Второй металл содержится в количестве: 74.99999999999997 кг
Третий металл содержится в количестве: 87.49999999999994 кг 

[37.5 75.  87.5]
